#include "utils.h"

const char *Genie_Status_ToString(Genie_Status_t status) {
  switch (status) {
  case GENIE_STATUS_SUCCESS:
    return "GENIE_STATUS_SUCCESS";
  case GENIE_STATUS_ERROR_GENERAL:
    return "GENIE_STATUS_ERROR_GENERAL";
  case GENIE_STATUS_ERROR_INVALID_ARGUMENT:
    return "GENIE_STATUS_ERROR_INVALID_ARGUMENT";
  case GENIE_STATUS_ERROR_MEM_ALLOC:
    return "GENIE_STATUS_ERROR_MEM_ALLOC";
  case GENIE_STATUS_ERROR_INVALID_CONFIG:
    return "GENIE_STATUS_ERROR_INVALID_CONFIG";
  case GENIE_STATUS_ERROR_INVALID_HANDLE:
    return "GENIE_STATUS_ERROR_INVALID_HANDLE";
  case GENIE_STATUS_ERROR_QUERY_FAILED:
    return "GENIE_STATUS_ERROR_QUERY_FAILED";
  case GENIE_STATUS_ERROR_JSON_FORMAT:
    return "GENIE_STATUS_ERROR_JSON_FORMAT";
  case GENIE_STATUS_ERROR_JSON_SCHEMA:
    return "GENIE_STATUS_ERROR_JSON_SCHEMA";
  case GENIE_STATUS_ERROR_JSON_VALUE:
    return "GENIE_STATUS_ERROR_JSON_VALUE";
  default:
    return "UNKNOWN_GENIE_STATUS";
  }
}
