#include "utils.h"
#include <stdlib.h>

const char *Genie_Status_ToString(Genie_Status_t status) {
  switch (status) {
  case GENIE_STATUS_SUCCESS:
    return "GENIE_STATUS_SUCCESS";
  case GENIE_STATUS_WARNING_ABORTED:
    return "GENIE_STATUS_WARNING_ABORTED";
  case GENIE_STATUS_WARNING_BOUND_HANDLE:
    return "GENIE_STATUS_WARNING_BOUND_HANDLE";
  case GENIE_STATUS_WARNING_PAUSED:
    return "GENIE_STATUS_WARNING_PAUSED";
  case GENIE_STATUS_WARNING_CONTEXT_EXCEEDED:
    return "GENIE_STATUS_WARNING_CONTEXT_EXCEEDED";
  case GENIE_STATUS_ERROR_GENERAL:
    return "GENIE_STATUS_ERROR_GENERAL";
  case GENIE_STATUS_ERROR_INVALID_ARGUMENT:
    return "GENIE_STATUS_ERROR_INVALID_ARGUMENT";
  case GENIE_STATUS_ERROR_MEM_ALLOC:
    return "GENIE_STATUS_ERROR_MEM_ALLOC";
  case GENIE_STATUS_ERROR_INVALID_CONFIG:
    return "GENIE_STATUS_ERROR_INVALID_CONFIG";
  case GENIE_STATUS_ERROR_INVALID_HANDLE:
    return "GENIE_STATUS_ERROR_INVALID_HANDLE";
  case GENIE_STATUS_ERROR_QUERY_FAILED:
    return "GENIE_STATUS_ERROR_QUERY_FAILED";
  case GENIE_STATUS_ERROR_JSON_FORMAT:
    return "GENIE_STATUS_ERROR_JSON_FORMAT";
  case GENIE_STATUS_ERROR_JSON_SCHEMA:
    return "GENIE_STATUS_ERROR_JSON_SCHEMA";
  case GENIE_STATUS_ERROR_JSON_VALUE:
    return "GENIE_STATUS_ERROR_JSON_VALUE";
  case GENIE_STATUS_ERROR_GENERATE_FAILED:
    return "GENIE_STATUS_ERROR_GENERATE_FAILED";
  case GENIE_STATUS_ERROR_GET_HANDLE_FAILED:
    return "GENIE_STATUS_ERROR_GET_HANDLE_FAILED";
  case GENIE_STATUS_ERROR_APPLY_CONFIG_FAILED:
    return "GENIE_STATUS_ERROR_APPLY_CONFIG_FAILED";
  case GENIE_STATUS_ERROR_SET_PARAMS_FAILED:
    return "GENIE_STATUS_ERROR_SET_PARAMS_FAILED";
  case GENIE_STATUS_ERROR_BOUND_HANDLE:
    return "GENIE_STATUS_ERROR_BOUND_HANDLE";
  default:
    return "UNKNOWN_GENIE_STATUS";
  }
}

void alloc_json_data(size_t size, const char** data) {
  *data = (char*)malloc(size);
}
